Revert "BUG-22139 oozie is still failing with NoSuchMethodError: method java.util.Properties.stringPropertyNames with signature Ljava.util.Set"
This reverts commit 1422b231307160867bde6d102d8ef7112a09a40b.